"use server";

export const getJuniorsData = async () => {
  return dummyData;
};

const dummyData = [
  {
    id: 1,
    name: "Alex",
    email: "alex.johnson@example.com",
    contributor: "John Smith",
    status: "in progress",
    joinedOn: "2023-01-10",
    projects: 3,
    points: 300,
    activeProjects: 2,
    completedProjects: 3,
  },
  {
    id: 2,
    name: "Alex",
    email: "alex.johnson@example.com",
    contributor: "John Smith",
    status: "in progress",
    joinedOn: "2023-01-10",
    projects: 3,
    points: 300,
    activeProjects: 2,
    completedProjects: 3,
  },
  {
    id: 3,
    name: "Alex",
    email: "alex.johnson@example.com",
    contributor: "John Smith",
    status: "in progress",
    joinedOn: "2023-01-10",
    projects: 3,
    points: 300,
    activeProjects: 2,
    completedProjects: 3,
  },
  {
    id: 4,
    name: "Alex",
    email: "alex.johnson@example.com",
    contributor: "John Smith",
    status: "in progress",
    joinedOn: "2023-01-10",
    projects: 3,
    points: 300,
    activeProjects: 2,
    completedProjects: 3,
  },
  {
    id: 5,
    name: "Alex",
    email: "alex.johnson@example.com",
    contributor: "John Smith",
    status: "in progress",
    joinedOn: "2023-01-10",
    projects: 3,
    points: 300,
    activeProjects: 2,
    completedProjects: 3,
  },
  {
    id: 6,
    name: "Alex",
    email: "alex.johnson@example.com",
    contributor: "John Smith",
    status: "in progress",
    joinedOn: "2023-01-10",
    projects: 3,
    points: 300,
    activeProjects: 2,
    completedProjects: 3,
  },
  {
    id: 7,
    name: "Alex",
    email: "alex.johnson@example.com",
    contributor: "John Smith",
    status: "in progress",
    joinedOn: "2023-01-10",
    projects: 3,
    points: 300,
    activeProjects: 2,
    completedProjects: 3,
  },
  {
    id: 8,
    name: "Alex",
    email: "alex.johnson@example.com",
    contributor: "John Smith",
    status: "active",
    joinedOn: "2023-01-10",
    projects: 3,
    points: 300,
    activeProjects: 2,
    completedProjects: 3,
  },
  {
    id: 9,
    name: "Alex",
    email: "alex.johnson@example.com",
    contributor: "John Smith",
    status: "active",
    joinedOn: "2023-01-10",
    projects: 3,
    points: 300,
    activeProjects: 2,
    completedProjects: 3,
  },
  {
    id: 10,
    name: "Alex",
    email: "alex.johnson@example.com",
    contributor: "John Smith",
    status: "active",
    joinedOn: "2023-01-10",
    projects: 3,
    points: 300,
    activeProjects: 2,
    completedProjects: 3,
  },
  {
    id: 11,
    name: "Alex",
    email: "alex.johnson@example.com",
    contributor: "John Smith",
    status: "active",
    joinedOn: "2023-01-10",
    projects: 3,
    points: 300,
    activeProjects: 2,
    completedProjects: 3,
  },
  {
    id: 12,
    name: "Alex",
    email: "alex.johnson@example.com",
    contributor: "John Smith",
    status: "active",
    joinedOn: "2023-01-10",
    projects: 3,
    points: 300,
    activeProjects: 2,
    completedProjects: 3,
  },
];
