export const projectsData = [
  {
    id: 1,
    category: 'Web Development',
    title: 'Build Your First Website',
    image: '/images/featued-Project-image.svg',
    description: 'Create a personal website using HTML & CSS',
    rating: 5,
    difficulty: 'Solo',
    isFree: false,
  },
  {
    id: 2,
    category: 'Web Development',
    title: 'Build Your First Website',
    image: '/images/featued-Project-image.svg',
    description: 'Create a personal website using HTML & CSS',
    rating: 5,
    difficulty: 'Solo',
    isFree: false,
  },
  {
    id: 3,
    category: 'Web Development',
    title: 'Build Your First Website',
    image: '/images/featued-Project-image.svg',
    description: 'Create a personal website using HTML & CSS',
    rating: 5,
    difficulty: 'Solo',
    isFree: true,
  },
  {
    id: 4,
    category: 'Web Development',
    title: 'Build Your First Website',
    image: '/images/featued-Project-image.svg',
    description: 'Create a personal website using HTML & CSS',
    rating: 5,
    difficulty: 'Solo',
    isFree: false,
  },
  {
    id: 5,
    category: 'Mobile Development',
    title: 'Build Your First Website',
    image: '/images/featued-Project-image.svg',
    description: 'Build your first mobile app with React Native',
    rating: 4,
    difficulty: 'Solo',
    isFree: true,
  },
  {
    id: 6,
    category: 'Data Science',
    title: 'Build Your First Website',
    image: '/images/featued-Project-image.svg',
    description: 'Learn data analysis with pandas and matplotlib',
    rating: 5,
    difficulty: 'Intermediate',
    isFree: false,
  },
  {
    id: 7,
    category: 'Web Development',
    title: 'Build Your First Website',
    image: '/images/featued-Project-image.svg',
    description: 'Master modern JavaScript concepts and patterns',
    rating: 4,
    difficulty: 'Advanced',
    isFree: false,
  },
  {
    id: 8,
    category: 'Mobile Development',
    title: 'Build Your First Website',
    image: '/images/featued-Project-image.svg',
    description: 'Create iOS apps with Swift and UIKit',
    rating: 5,
    difficulty: 'Advanced',
    isFree: true,
  },
];

export const featuredProjectTabs = [
  {
    title: 'All',
    link: '/home',
  },
  {
    title: 'Solo Projects',
    link: '/home#solo-projects',
  },
  {
    title: 'Team Projects',
    link: '/home#team-projects',
  },
  {
    title: 'Web Development',
    link: '/home#web-development',
  },
  {
    title: 'Coding',
    link: '/home#coding',
  },
];
