variables:
  pnpm_config_cache: $(Pipeline.Workspace)/.pnpm-store
  group: default

trigger:
  - main

pr:
  branches:
    include:
      - "*"

pool:
  vmImage: ubuntu-latest

steps:
  # Checkout the repository and submodules recursively.
  - checkout: self
    displayName: "Checkout repository with submodules"

  - task: NodeTool@0
    inputs:
      versionSpec: "20.x"
    displayName: "Install Node.js"

  - script: |
      echo "Before: corepack version => $(corepack --version || echo 'not installed')"
      npm install -g corepack@latest
      echo "After : corepack version => $(corepack --version)"
      corepack enable
      pnpm --version
    displayName: "Install pnpm"

  - task: Cache@2
    displayName: "Cache .next/cache"
    inputs:
      key: next | $(Agent.OS) | pnpm-lock.yaml
      path: "$(System.DefaultWorkingDirectory)/.next/cache"

  - task: Cache@2
    displayName: "Cache pnpm"
    inputs:
      key: 'pnpm | "$(Agent.OS)" | pnpm-lock.yaml'
      path: $(pnpm_config_cache)

  - script: |
      npm install --global corepack@latest
      corepack enable
      corepack prepare pnpm@latest-10 --activate
      pnpm config set store-dir $(pnpm_config_cache)
    displayName: "Setup pnpm"

  - script: |
      pnpm install
      pnpm run build
    displayName: "pnpm install and build"
