import { Tab, TabGroup, TabList, TabPanel, TabPanels } from "@headlessui/react";
import { ProjectsHeader } from "./ProjectsHeader";
import { tabClassName, tabListClassName } from "@styles";
import { ProjectsCarousel } from "./ProjectCarousel";
import { ProjectType } from "../../types";

export const Projects = async () => {
  return (
    <>
      <ProjectsHeader />
      <TabGroup className="pt-8">
        <div className="flex justify-center px-4">
          <TabList className={tabListClassName}>
            {projects.map(({ name }) => {
              return (
                <Tab className={tabClassName} key={name}>
                  {name}
                </Tab>
              );
            })}
          </TabList>
        </div>
        <TabPanels className="pt-10">
          {projects.map(({ projects, name }) => {
            return (
              <TabPanel key={name}>
                <ProjectsCarousel projects={projects} />
              </TabPanel>
            );
          })}
        </TabPanels>
      </TabGroup>
    </>
  );
};

const projects = [
  {
    name: "All",
    projects: [
      {
        id: "1",
        category: "Web Devlopement",
        imageUrl: "/images/featued-Project-image.svg",
        description: "Your first website with flask (Part 1,2,3)",
        rating: 4,
        projectType: "solo" as ProjectType,
        isFree: true,
        title: "Build Your first website",
      },
      {
        id: "2",
        category: "Web Devlopement",
        imageUrl: "/images/featued-Project-image.svg",
        description: "Your first website with flask (Part 1,2,3)",
        rating: 4,
        projectType: "solo" as ProjectType,
        isFree: true,
        title: "Build Your first website",
      },
      {
        id: "3",
        category: "Web Devlopement",
        imageUrl: "/images/featued-Project-image.svg",
        description: "Your first website with flask (Part 1,2,3)",
        rating: 4,
        projectType: "solo" as ProjectType,
        isFree: true,
        title: "Build Your first website",
      },
      {
        id: "4",
        category: "Web Devlopement",
        imageUrl: "/images/featued-Project-image.svg",
        description: "Your first website with flask (Part 1,2,3)",
        rating: 4,
        projectType: "solo" as ProjectType,
        isFree: true,
        title: "Build Your first website",
      },
      {
        id: "5",
        category: "Web Devlopement",
        imageUrl: "/images/featued-Project-image.svg",
        description: "Your first website with flask (Part 1,2,3)",
        rating: 4,
        projectType: "solo" as ProjectType,
        isFree: true,
        title: "Build Your first website",
      },
      {
        id: "6",
        category: "Web Devlopement",
        imageUrl: "/images/featued-Project-image.svg",
        description: "Your first website with flask (Part 1,2,3)",
        rating: 4,
        projectType: "solo" as ProjectType,
        isFree: true,
        title: "Build Your first website",
      },
      {
        id: "7",
        category: "Web Devlopement",
        imageUrl: "/images/featued-Project-image.svg",
        description: "Your first website with flask (Part 1,2,3)",
        rating: 4,
        projectType: "solo" as ProjectType,
        isFree: true,
        title: "Build Your first website",
      },
      {
        id: "8",
        category: "Web Devlopement",
        imageUrl: "/images/featued-Project-image.svg",
        description: "Your first website with flask (Part 1,2,3)",
        rating: 4,
        projectType: "solo" as ProjectType,
        isFree: true,
        title: "Build Your first website",
      },
    ],
  },
  {
    name: "Solo Projects",
    projects: [
      {
        id: "1",
        category: "Solo",
        imageUrl: "/images/featued-Project-image.svg",
        description: "Your first website with flask (Part 1,2,3)",
        rating: 4,
        projectType: "solo" as ProjectType,
        isFree: true,
        title: "Build Your first website",
      },
      {
        id: "2",
        category: "Solo",
        imageUrl: "/images/featued-Project-image.svg",
        description: "Your first website with flask (Part 1,2,3)",
        rating: 4,
        projectType: "solo" as ProjectType,
        isFree: true,
        title: "Build Your first website",
      },
      {
        id: "3",
        category: "Solo",
        imageUrl: "/images/featued-Project-image.svg",
        description: "Your first website with flask (Part 1,2,3)",
        rating: 4,
        projectType: "solo" as ProjectType,
        isFree: true,
        title: "Build Your first website",
      },
      {
        id: "4",
        category: "Solo",
        imageUrl: "/images/featued-Project-image.svg",
        description: "Your first website with flask (Part 1,2,3)",
        rating: 4,
        projectType: "solo" as ProjectType,
        isFree: true,
        title: "Build Your first website",
      },
      {
        id: "5",
        category: "Solo",
        imageUrl: "/images/featued-Project-image.svg",
        description: "Your first website with flask (Part 1,2,3)",
        rating: 4,
        projectType: "solo" as ProjectType,
        isFree: true,
        title: "Build Your first website",
      },
      {
        id: "6",
        category: "Solo",
        imageUrl: "/images/featued-Project-image.svg",
        description: "Your first website with flask (Part 1,2,3)",
        rating: 4,
        projectType: "solo" as ProjectType,
        isFree: true,
        title: "Build Your first website",
      },
      {
        id: "7",
        category: "Solo",
        imageUrl: "/images/featued-Project-image.svg",
        description: "Your first website with flask (Part 1,2,3)",
        rating: 4,
        projectType: "solo" as ProjectType,
        isFree: true,
        title: "Build Your first website",
      },
      {
        id: "8",
        category: "Solo",
        imageUrl: "/images/featued-Project-image.svg",
        description: "Your first website with flask (Part 1,2,3)",
        rating: 4,
        projectType: "solo" as ProjectType,
        isFree: true,
        title: "Build Your first website",
      },
    ],
  },
  {
    name: "Team Projects",
    projects: [
      {
        id: "1",
        category: "Team",
        imageUrl: "/images/featued-Project-image.svg",
        description: "Your first website with flask (Part 1,2,3)",
        rating: 4,
        projectType: "solo" as ProjectType,
        isFree: true,
        title: "Build Your first website",
      },
      {
        id: "2",
        category: "Team",
        imageUrl: "/images/featued-Project-image.svg",
        description: "Your first website with flask (Part 1,2,3)",
        rating: 4,
        projectType: "solo" as ProjectType,
        isFree: true,
        title: "Build Your first website",
      },
      {
        id: "3",
        category: "Team",
        imageUrl: "/images/featued-Project-image.svg",
        description: "Your first website with flask (Part 1,2,3)",
        rating: 4,
        projectType: "solo" as ProjectType,
        isFree: true,
        title: "Build Your first website",
      },
      {
        id: "4",
        category: "Team",
        imageUrl: "/images/featued-Project-image.svg",
        description: "Your first website with flask (Part 1,2,3)",
        rating: 4,
        projectType: "solo" as ProjectType,
        isFree: true,
        title: "Build Your first website",
      },
      {
        id: "5",
        category: "Team",
        imageUrl: "/images/featued-Project-image.svg",
        description: "Your first website with flask (Part 1,2,3)",
        rating: 4,
        projectType: "solo" as ProjectType,
        isFree: true,
        title: "Build Your first website",
      },
      {
        id: "6",
        category: "Team",
        imageUrl: "/images/featued-Project-image.svg",
        description: "Your first website with flask (Part 1,2,3)",
        rating: 4,
        projectType: "solo" as ProjectType,
        isFree: true,
        title: "Build Your first website",
      },
      {
        id: "7",
        category: "Team",
        imageUrl: "/images/featued-Project-image.svg",
        description: "Your first website with flask (Part 1,2,3)",
        rating: 4,
        projectType: "solo" as ProjectType,
        isFree: true,
        title: "Build Your first website",
      },
      {
        id: "8",
        category: "Team",
        imageUrl: "/images/featued-Project-image.svg",
        description: "Your first website with flask (Part 1,2,3)",
        rating: 4,
        projectType: "solo" as ProjectType,
        isFree: true,
        title: "Build Your first website",
      },
    ],
  },
  {
    name: "Web Devlopement",
    projects: [
      {
        id: "1",
        category: "Web Devlopement",
        imageUrl: "/images/featued-Project-image.svg",
        description: "Your first website with flask (Part 1,2,3)",
        rating: 4,
        projectType: "solo" as ProjectType,
        isFree: true,
        title: "Build Your first website",
      },
      {
        id: "2",
        category: "Web Devlopement",
        imageUrl: "/images/featued-Project-image.svg",
        description: "Your first website with flask (Part 1,2,3)",
        rating: 4,
        projectType: "solo" as ProjectType,
        isFree: true,
        title: "Build Your first website",
      },
      {
        id: "3",
        category: "Web Devlopement",
        imageUrl: "/images/featued-Project-image.svg",
        description: "Your first website with flask (Part 1,2,3)",
        rating: 4,
        projectType: "solo" as ProjectType,
        isFree: true,
        title: "Build Your first website",
      },
      {
        id: "4",
        category: "Web Devlopement",
        imageUrl: "/images/featued-Project-image.svg",
        description: "Your first website with flask (Part 1,2,3)",
        rating: 4,
        projectType: "solo" as ProjectType,
        isFree: true,
        title: "Build Your first website",
      },
      {
        id: "5",
        category: "Web Devlopement",
        imageUrl: "/images/featued-Project-image.svg",
        description: "Your first website with flask (Part 1,2,3)",
        rating: 4,
        projectType: "solo" as ProjectType,
        isFree: true,
        title: "Build Your first website",
      },
      {
        id: "6",
        category: "Web Devlopement",
        imageUrl: "/images/featued-Project-image.svg",
        description: "Your first website with flask (Part 1,2,3)",
        rating: 4,
        projectType: "solo" as ProjectType,
        isFree: true,
        title: "Build Your first website",
      },
      {
        id: "7",
        category: "Web Devlopement",
        imageUrl: "/images/featued-Project-image.svg",
        description: "Your first website with flask (Part 1,2,3)",
        rating: 4,
        projectType: "solo" as ProjectType,
        isFree: true,
        title: "Build Your first website",
      },
      {
        id: "8",
        category: "Web Devlopement",
        imageUrl: "/images/featued-Project-image.svg",
        description: "Your first website with flask (Part 1,2,3)",
        rating: 4,
        projectType: "solo" as ProjectType,
        isFree: true,
        title: "Build Your first website",
      },
    ],
  },
  {
    name: "Coding",
    projects: [
      {
        id: "1",
        category: "Coding",
        imageUrl: "/images/featued-Project-image.svg",
        description: "Your first website with flask (Part 1,2,3)",
        rating: 4,
        projectType: "solo" as ProjectType,
        isFree: true,
        title: "Build Your first website",
      },
      {
        id: "2",
        category: "Coding",
        imageUrl: "/images/featued-Project-image.svg",
        description: "Your first website with flask (Part 1,2,3)",
        rating: 4,
        projectType: "solo" as ProjectType,
        isFree: true,
        title: "Build Your first website",
      },
      {
        id: "3",
        category: "Coding",
        imageUrl: "/images/featued-Project-image.svg",
        description: "Your first website with flask (Part 1,2,3)",
        rating: 4,
        projectType: "solo" as ProjectType,
        isFree: true,
        title: "Build Your first website",
      },
      {
        id: "4",
        category: "Coding",
        imageUrl: "/images/featued-Project-image.svg",
        description: "Your first website with flask (Part 1,2,3)",
        rating: 4,
        projectType: "solo" as ProjectType,
        isFree: true,
        title: "Build Your first website",
      },
      {
        id: "5",
        category: "Coding",
        imageUrl: "/images/featued-Project-image.svg",
        description: "Your first website with flask (Part 1,2,3)",
        rating: 4,
        projectType: "solo" as ProjectType,
        isFree: true,
        title: "Build Your first website",
      },
      {
        id: "6",
        category: "Coding",
        imageUrl: "/images/featued-Project-image.svg",
        description: "Your first website with flask (Part 1,2,3)",
        rating: 4,
        projectType: "solo" as ProjectType,
        isFree: true,
        title: "Build Your first website",
      },
      {
        id: "7",
        category: "Coding",
        imageUrl: "/images/featued-Project-image.svg",
        description: "Your first website with flask (Part 1,2,3)",
        rating: 4,
        projectType: "solo" as ProjectType,
        isFree: true,
        title: "Build Your first website",
      },
      {
        id: "8",
        category: "Coding",
        imageUrl: "/images/featued-Project-image.svg",
        description: "Your first website with flask (Part 1,2,3)",
        rating: 4,
        projectType: "solo" as ProjectType,
        isFree: true,
        title: "Build Your first website",
      },
    ],
  },
];
