export { AmazonIcon } from './AmazonIcon';
export { AppleIcon } from './AppleIcon';
export { CalendarIcon } from './CalendarIcon';
export { ChatIcon } from './ChatIcon';
export { DiamondIcon } from './DiamondIcon';
export { DocumentIcon } from './DocumentIcon';
export { FireIcon } from './FireIcon';
export { GoogleIcon } from './GoogleIcon';
export { HomeIcon } from './HomeIcon';
export { HourGlassIcon } from './HourGlassIcon';
export { LogoutIcon } from './LogoutIcon';
export { MetaIcon } from './MetaIcon';
export { MicrosoftIcon } from './MicrosoftIcon';
export { MoneyIcon } from './MoneyIcon';
export { SettingsIcon } from './SettingsIcon';
export { StarIcon } from './StarIcon';
export { UserIcon } from './UserIcon';
export { WalletIcon } from './WalletIcon';

